[package]
name = "jukebox_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [".", "jukebox_axum", "jukebox_yew", "my_youtube_extractor"]

[dependencies]
